### ISSUE TITLE
k = 2

### ISSUE THREAD

**Issue by MathieuMonsecour** [pcoenen/Algebra-solutions-excercises#6]
Op pagina 47 denk ik dat k = 2 in plaats van k = 7

\textbf{1)} $7^k \text{ mod } 12 = 1 \Rightarrow k = 7$. \\

vervangen met

\textbf{1)} $7^k \text{ mod } 12 = 1 \Rightarrow k = 2$. \\

**Comment by pcoenen** [comment]
Bedankt ! Is gefixed !
